### ISSUE TITLE
Unknown model component: temp_doeclim

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector-SA-npar#1]
I am able to build the dev doeclim bracnh.
 ``` 
$ git branch
* dev_doeclim
  master
 ````
Hector is able to run when I use the ini example files included in the `hector/input` directory but when I try to include the temp_doeclim component in the ini file or try to run the `hector-SA-2par/code/B.ini_generation_and_pic_run.R` I get the following error message 

``` 

$ ./source/hector ./input/hector_rcp45.ini
Mon Jan 22 11:56:44 2018:NOTICE:printLogHeader: hector version 1.1
Mon Jan 22 11:56:44 2018:NOTICE:main: hector wrapper start
Mon Jan 22 11:56:44 2018:DEBUG:h_reader: h_reader created for ./input/hector_rcp45.ini
Mon Jan 22 11:56:44 2018:NOTICE:parse: Parsing ./input/hector_rcp45.ini
Mon Jan 22 11:56:44 2018:NOTICE:main: Creating and initializing the core.
Mon Jan 22 11:56:44 2018:NOTICE:printLogHeader: hector version 1.1
Mon Jan 22 11:56:44 2018:NOTICE:main: Setting data in the core.
Mon Jan 22 11:56:44 2018:WARNING:setData: Disabling onelineocean
Mon Jan 22 11:56:44 2018:WARNING:setData: Disabling temperature
* Program exception: Assertion failed: Unknown model component: temp_doeclim*
* Function getComponentByName, file core.cpp, line 469
``` 

@fengly20 have you run into `Program exception: Assertion failed: Unknown model component: temp_doeclim` before? If so how did you resolve it?

**Comment by fengly20** [comment]
It's weird...as looking at the first line of the error message it indicates that the `ini` file used for this run is called `hector_rcp45.ini`. However that seems not an `ini` file generated by script `B.ini_generation_and_pic_run.R`. The `ini` file generated by the script should have a name looks like `hector_SA0001.ini` or something. 

As for the error, my guess is that file `hector_rcp45.ini` cannot be used to run `doeclim` version of hector (or vice versa).

**Comment by kdorheim** [comment]
Oh sorry the error message I posted is some what misleading. When I run the `B_jobscipt.sh` I get 
``` Current time : Mon Jan 22 11:28:40 PST 2018
/pic/projects/GCAM/Dorheim/CMS/hector
Mon Jan 22 11:28:42 2018:NOTICE:printLogHeader: hector version 1.1
Mon Jan 22 11:28:42 2018:NOTICE:main: hector wrapper start
Mon Jan 22 11:28:42 2018:DEBUG:h_reader: h_reader created for /pic/projects/GCAM/Dorheim/CMS/hector/input/hectorSA-0001.ini
Mon Jan 22 11:28:42 2018:NOTICE:parse: Parsing /pic/projects/GCAM/Dorheim/CMS/hector/input/hectorSA-0001.ini
Mon Jan 22 11:28:42 2018:NOTICE:main: Creating and initializing the core.
Mon Jan 22 11:28:42 2018:NOTICE:printLogHeader: hector version 1.1
Mon Jan 22 11:28:42 2018:NOTICE:main: Setting data in the core.
Mon Jan 22 11:28:42 2018:WARNING:setData: Disabling onelineocean
Mon Jan 22 11:28:43 2018:WARNING:setData: Disabling temperature
* Program exception: Assertion failed: Unknown model component: temp_doeclim
* Function getComponentByName, file core.cpp, line 469
Error in file(file, "rt") : cannot open the connection
Calls: lapply -> FUN -> read.csv -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/pic/projects/GCAM/Dorheim/CMS/hector/output/outputstream_hectorSA-0001.csv': No such file or directory
Execution halted
Current time : Mon Jan 22 11:28:43 PST 2018
```
The script fails because the `outputstream_hectorSA-0001.csv` was never written because `* Program exception: Assertion failed: Unknown model component: temp_doeclim*`

So it seems that there may be so issue caused by a new commit to the dev deoclim branch on Hector. Hopefully this issue will be resolved with the new release of Hector.

**Comment by fengly20** [comment]
I see. The default 'deoclim' ini file has changed in this [commit](https://github.com/JGCRI/hector/commit/c92f9e5a14bfb6ffd7339ce8e8678acf9819502d). I did not catch the update thus the default ini file template in `hector-SA-2par` is out of date.

**Comment by kdorheim** [comment]
I am in no rush to get the `hector-SA-2par` code running, we can wait to change the default ini template in `hector-SA-2par` until we hear about which version of Hector we should be using. 

Thanks for the help LY!

**Comment by fengly20** [comment]
Sounds good!
