### ISSUE TITLE
Investigate the carbon-cycle paramters 

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector-SA-npar#18]
Now we would like to look at the uncertainty contribution from the carbon-cycle parameters. 

Run Hector 5,000 times varying beta only 
Run Hector 5,000 times varying q10 only 
Run Hector 5,000 times varying q10 and beta together 

Keep s and diff constant at the default values. 

Hector --> observations --> GCAM??

**Comment by kdorheim** [comment]
Here are some preliminary figures for the n-par results. 
 
[preliminary _npar_results.docx](https://github.com/JGCRI/hector-SA-npar/files/2262856/preliminary._npar_results.docx)

**Comment by cahartin** [comment]
@kdorheim do we want to resurrect this?  I went through the preliminary results again and I don't see much other than - interactions of parameters matter....
