### ISSUE TITLE
Dn metric methodology

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector-SA-npar#19]
What is the difference between stacking the Dn metric results (in order for the run to count as passing the Hector results must have a significant Dn value for each variable) and optimizing Dn for all three (the Dn metric must be significant for multiple variables at once?)

**Comment by kdorheim** [comment]
More runs are considered passing when we do the optimize multiple variables at once approach. The optimized approach passes an extra `104` Hector runs. All of the runs that pass through the stacked windows also pass through the optimized approach. 

#### Run Count
![image](https://user-images.githubusercontent.com/27299759/43903042-88d93268-9bb9-11e8-914a-3b8ae702ba9b.png)

#### Parameter Space
We only see a difference in the passing `beta` parameter space.
![image](https://user-images.githubusercontent.com/27299759/43903235-f9e79e90-9bb9-11e8-9abd-d90d0161e007.png)

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> param </th>
   <th style="text-align:left;"> filter </th>
   <th style="text-align:right;"> max </th>
   <th style="text-align:right;"> min </th>
   <th style="text-align:right;"> range </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;vertical-align: middle !important;" rowspan="2"> beta </td>
   <td style="text-align:left;"> optimized </td>
   <td style="text-align:right;"> 0.37695 </td>
   <td style="text-align:right;"> 0.07471 </td>
   <td style="text-align:right;"> 0.30224 </td>
  </tr>
  <tr>
   
   <td style="text-align:left;"> stacked </td>
   <td style="text-align:right;"> 0.34058 </td>
   <td style="text-align:right;"> 0.16919 </td>
   <td style="text-align:right;"> 0.17139 </td>
  </tr>
  <tr>
   <td style="text-align:left;vertical-align: middle !important;" rowspan="2"> diff </td>
   <td style="text-align:left;"> optimized </td>
   <td style="text-align:right;"> 3.99829 </td>
   <td style="text-align:right;"> 0.50299 </td>
   <td style="text-align:right;"> 3.49530 </td>
  </tr>
  <tr>
   
   <td style="text-align:left;"> stacked </td>
   <td style="text-align:right;"> 3.99829 </td>
   <td style="text-align:right;"> 0.51282 </td>
   <td style="text-align:right;"> 3.48547 </td>
  </tr>
  <tr>
   <td style="text-align:left;vertical-align: middle !important;" rowspan="2"> q10 </td>
   <td style="text-align:left;"> optimized </td>
   <td style="text-align:right;"> 4.99473 </td>
   <td style="text-align:right;"> 0.23164 </td>
   <td style="text-align:right;"> 4.76309 </td>
  </tr>
  <tr>
   
   <td style="text-align:left;"> stacked </td>
   <td style="text-align:right;"> 4.97773 </td>
   <td style="text-align:right;"> 0.23164 </td>
   <td style="text-align:right;"> 4.74609 </td>
  </tr>
  <tr>
   <td style="text-align:left;vertical-align: middle !important;" rowspan="2"> s </td>
   <td style="text-align:left;"> optimized </td>
   <td style="text-align:right;"> 3.95532 </td>
   <td style="text-align:right;"> 1.00586 </td>
   <td style="text-align:right;"> 2.94946 </td>
  </tr>
  <tr>
   
   <td style="text-align:left;"> stacked </td>
   <td style="text-align:right;"> 3.95532 </td>
   <td style="text-align:right;"> 1.00586 </td>
   <td style="text-align:right;"> 2.94946 </td>
  </tr>
</tbody>
</table>


#### Hector vs Obs

The optimized method includes some more that are outside the stacked run boundaries and also within the stacked boundaries.

![image](https://user-images.githubusercontent.com/27299759/43903549-b5259bbc-9bba-11e8-866a-f3d11829f381.png)

![image](https://user-images.githubusercontent.com/27299759/43903572-c080c6d0-9bba-11e8-8401-0531aa27b1ee.png)

![image](https://user-images.githubusercontent.com/27299759/43903589-c816e55a-9bba-11e8-8886-4c118f7765a0.png)

**Comment by kdorheim** [comment]
@cahartin do we want to stick with the stacked approach or the optimizing for multiple variables method moving forward?

**Comment by cahartin** [comment]
Cool figures!  I'm not sure at the moment. in the paper we pulled the method from, do they suggest one way over another?

**Comment by kdorheim** [comment]
The paper we pull from optimizes for multiple variables at once. 

We decided to use this stacked method so that we could try to evaluate the value each observational product contributes individually.

**Comment by cahartin** [comment]
right right.  What if we optimize 2 variables and 3 and see the difference? I think both ways are good, i don't know if i have a strong opinion either way....

**Comment by kdorheim** [comment]
sure, i can optimize for 2 variables at a time but I don't really understand what that would tell us, aren't we trying to get away form the all the observational filters story line and focus on the 3 observational product filter?

**Comment by cahartin** [comment]
yes yes i agree.  however, i was thinking that we could also use the optimizing technique to also look at the value of individual products.

**Comment by kdorheim** [comment]
the optimizing technique would come into play when we combine products not individual ones
