### ISSUE TITLE
 What does the hector temp vs time look like for those 2 runs compared to cmip5?

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector-SA-npar#21]

**Comment by kdorheim** [comment]
* What does the hector temp vs time look like compared to the cmip5 temp vs time? 
* What if we use the ESM/GCMs information in the Dn filtering process? What insights would that reveal? How different is that from the parameter space selected by the observational filtering process?

**Comment by cahartin** [comment]
I like the last question.  what if we use CMIP5 output as our filters for temp, co2 and npp, how do our results change?
