### ISSUE TITLE
update emissions

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector-SA-npar#25]
[Global Emissions](https://github.com/openclimatedata/global-emissions/tree/master/data)

we need [N2O from](https://www.pik-potsdam.de/paris-reality-check/primap-hist/#id=earth&entity=kyotoghgar4)
add up all of the sectors and countries into 1 global total

we need to disable: 
C6F14
HFC4310
HCF22
HCF141b
HCF142b

**Comment by cahartin** [comment]
rather than running out to 2100, let's stop hector at the end of these emissions ~2016

**Comment by kdorheim** [comment]
@cahartin How do we disable 
C6F14
HFC4310
HFC22
HFC141b
HFC142b?

**Comment by cahartin** [comment]
in the ini file under the component name  enable = 0

**Comment by kdorheim** [comment]
@cahartin 
```
[HFC4310_halocarbon]
tau=15.9
rho=0.0004 
HFC4310_emissions=csv:emissions/hist_emissions.csv
molarMass=252.0
```

would be like ?

```
[HFC4310_halocarbon]
enabled = 0
tau=15.9
rho=0.0004 
HFC4310_emissions=csv:emissions/hist_emissions.csv
molarMass=252.0
```

**Comment by kdorheim** [comment]
Alright for the record the N2O emissions are reported in Gt but GCAM Hector wants it inMtN2O-N/yr

**Comment by cahartin** [comment]
@kdorheim 
Gt N2O emissions to MtN2O-N = /1.57 * 1000
