### ISSUE TITLE
atmospheric CO2 concentrations

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector-SA-npar#4]
NOAA ESRL +- standard deviation

**Comment by kdorheim** [comment]
Related to #2

**Comment by kdorheim** [comment]
@cahartin some methodology questions for the NOAA CO2 observations filtering

* I used the interpolated values from the NOAA data set is that okay?
* The average sd was 1.927093 ppm, so when I creted the boundaries I did +/- 2 sd becasue that seemed small. 
* What is the window size we want to use in the moving average? It seems inconsistent for the different filters used, for temperature it was 15 but for co2 growth it was set to 7. Right now I have the atm CO2 window set equal to 7.

**Comment by cahartin** [comment]
1. yes
2. thanks!
3. good point - let's try 7 and 15.  at first thought I'd like to keep all the filters with same # of years.

**Comment by kdorheim** [comment]
3. Did a 7 and 15 year window on the NOAA and Hector CO2 data. With the 15 year moving average 5 more Hector runs passed the atmospheric CO2 filter.  The figure below shows the observation window using the two different moving average years, they are really only different at the beginning and end of the time series.

 
![image](https://user-images.githubusercontent.com/27299759/36814326-315953c6-1ca5-11e8-9569-751c826d2a97.png)

**Comment by kdorheim** [comment]
Now we want to take a look at the run count of what passes through the CO2 window and what happens when we run standalone hector with constrained CO2 (use the `lawdome_CO2.csv`)

**Comment by kdorheim** [comment]
### Run Count 

![image](https://user-images.githubusercontent.com/27299759/39933608-76795ae2-5511-11e8-9a48-f795fda49654.png)

When we constrain the CO2 cycle using the `lawdome_CO2.csv` file we see that more Hector runs pass through the NOAA atm CO2 and the CO2 growth observation windows.

### Parameter Space 

![image](https://user-images.githubusercontent.com/27299759/39933747-cfc8b8ae-5511-11e8-8802-58ccae9179d9.png)

When the CO2 cycle is constrained the beta parameter space is not narrowed down to two inconsistent spaces and s is narrowed down by the temperature filter. 

### Question 

* Do we really want to constrain the CO2 cycle if that means that the C-cycle parameters are no longer being used during the period we have data products for?? :thinking:
