### ISSUE TITLE
literature review

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector-SA-npar#6]
I haven't thoroughly combed the literature. Can we start to compile papers that would be relevant?
1. carbon cycle uncertainty
2. simple climate model uncertainty characterization
3. economic impacts from uncertainty

**Comment by cahartin** [comment]
http://iopscience.iop.org/article/10.1088/1748-9326/7/2/024002/meta

**Comment by kdorheim** [comment]
~https://journals.ametsoc.org/doi/full/10.1175/JCLI-D-12-00579.1~ -- not that relevant

**Comment by cahartin** [comment]
@kdorheim there seems to be some recent literature about having more room so speak to reach 2 degrees.  I'm wondering if other people are seeing similar things to us (low temperature change for the 3 products).  Can you do a little digging. I'm thinking joeri rogelj published something recently in Nature.  Kate and Haewon might have some insights as well.
