### ISSUE TITLE
Figures for UIUC

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector-SA-npar#7]
- [x] all 50,00 Hector runs - mean and spread for temperature - maybe....that's probably overkill
- [x] plot of temperature observations on top of Hector runs - probably just the filtered runs
- [x] plot of atmo observations on top of Hector runs
- [x] plot of land flux observations on top of Hector runs
- [x] bar chart of hector runs with filtered parameters
- [x] parameter vs temperature or parameter vs CO2 plots

GCAM figures - for 2p6 overshoot
- [ ] Global mean temperature
- [ ] radiative forcing
- [ ] global CO2 emissions
- [ ]  carbon price
- [ ] CO2 concentrations

**Comment by kdorheim** [comment]
@cahartin
*  Is there a date you would like the figures by? 
* For the observation vs hector run figures do you want the figure to look at just the obs years or do you want to show the whole hector run?

**Comment by cahartin** [comment]
the gcam ones will take us a little longer since we are stuck on running in.  
for the hector ones, lets say next week and the whole run to start?  They don't have to be perfect, just a starting point.

**Comment by kdorheim** [comment]
@cahartin for the obs vs Hector am I plotting the raw values or the moving average values?

**Comment by cahartin** [comment]
the moving average is good.

**Comment by kdorheim** [comment]
Figures are made by `UIUC_figs.R`
