### ISSUE TITLE
Atm CO2 and Land Flux filter

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector-SA-npar#9]
Is is possible to find a methodology, threshold criteria / moving average year length that allows for some Hector runs to pass through  an Atm CO2 and Land Flux filter?

**Comment by kdorheim** [comment]
@cahartin Well when we drop the threshold down to 40% and we start to see a few runs pass through both the atm CO2 and the land flux observation windows. It doesn't look like changing the length of the moving average years does much. 

![image](https://user-images.githubusercontent.com/27299759/39941907-fccfebb4-552b-11e8-95ab-471665de66fc.png)

**Comment by cahartin** [comment]
hummm....thanks!

**Comment by kdorheim** [comment]
yea @cahartin I am not sure how you want to proceed

**Comment by kdorheim** [comment]
We're moving away from the threshold methodology so don't anticipate this to be an issue...
